pipeline:
  #doc:
  #  image: asciidoctor/docker-asciidoctor
  #  secrets: [ rsync_password ]
  #  commands:
  #    - apk add --no-cache libxslt docbook-xsl rsync
  #    - "(cd _doc/guide && make && make deploy; )"

  test:
    image: golang:latest
    commands:
      - export GOPATH=/drone
      - export CGO_ENABLED=0
      - export PEBBLE_VA_ALWAYS_VALID=1
      - .drone/script
